model:
    arch: fcn8s
data:
    dataset: isic18
    train_split: training
    val_split: test
    img_rows: 512
    img_cols: 512
    path: /home/bijan/Workspace/Python/pytorch-semseg/data/ISIC18
training:
    train_iters: 93400
    batch_size: 1
    val_interval: 5000
    n_workers: 8
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-5
        weight_decay: 0.0016
        momentum: 0.9
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: fcn8s_unet_best_model.pkl