model:
    arch: unet
data:
    dataset: isic18
    train_split: training
    val_split: validation
    img_rows: 572
    img_cols: 572
    path: /home/bijan/Workspace/Python/pytorch-semseg/data/ISIC18/
training:
    train_iters: 10000
    batch_size: 16
    val_interval: 1000
    n_workers: 8
    print_interval: 10
    optimizer:
        name: 'sgd'
        lr: 1.0e-7
        weight_decay: 0.0005
        momentum: 0.9
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: unet_isic18_best_model.pkl