model:
    arch: unet
data:
    dataset: isic18
    train_split: training
    val_split: test
    img_rows: 572
    img_cols: 572
    path: /home/bijan/Workspace/Python/pytorch-semseg/data/ISIC18
training:
    train_iters: 10000
    batch_size: 1
    val_interval: 1000
    n_workers: 4
    print_interval: 10
    optimizer:
        name: 'adam'
        lr: 1.0e-3
    loss:
        name: 'bootstrapped_cross_entropy'
        size_average: True
        K: 327184
    lr_schedule:
    resume: unet_isic18_best_model.pkl